version: "3.8"

services:
  app:
    container_name: hacktoberfest-leaderboard
    image: hacktoberfest-leaderboard
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - 8080:8080
